/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MokesciaiIndexRouteImport } from './routes/mokesciai/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MokesciaiIndexRoute = MokesciaiIndexRouteImport.update({
  id: '/mokesciai/',
  path: '/mokesciai/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mokesciai': typeof MokesciaiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mokesciai': typeof MokesciaiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mokesciai/': typeof MokesciaiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mokesciai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mokesciai'
  id: '__root__' | '/' | '/mokesciai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MokesciaiIndexRoute: typeof MokesciaiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mokesciai/': {
      id: '/mokesciai/'
      path: '/mokesciai'
      fullPath: '/mokesciai'
      preLoaderRoute: typeof MokesciaiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MokesciaiIndexRoute: MokesciaiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
