/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MokesciaiIndexRouteImport } from './routes/mokesciai/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'

const MokesciaiIndexRoute = MokesciaiIndexRouteImport.update({
  id: '/mokesciai/',
  path: '/mokesciai/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeIndexRoute
  '/mokesciai': typeof MokesciaiIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeIndexRoute
  '/mokesciai': typeof MokesciaiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home/': typeof HomeIndexRoute
  '/mokesciai/': typeof MokesciaiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/mokesciai'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/mokesciai'
  id: '__root__' | '/home/' | '/mokesciai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  MokesciaiIndexRoute: typeof MokesciaiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mokesciai/': {
      id: '/mokesciai/'
      path: '/mokesciai'
      fullPath: '/mokesciai'
      preLoaderRoute: typeof MokesciaiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  MokesciaiIndexRoute: MokesciaiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
